[theme]
primaryColor = "#0051FF"   # Blu Elettrico acceso
backgroundColor = "#FFFFFF" # Bianco assoluto
secondaryBackgroundColor = "#F0F2F6" # Grigio chiarissimo per le schede
textColor = "#000000"       # Testo nero
font = "sans serif"
